/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;


import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @authors Jonathan, Arthur e Gabriel at DotTech technologies 2017(C)
 */
public class Login extends javax.swing.JFrame {
public int consultor = 0;
    ValidaLog v = new ValidaLog();
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setSize(610,455);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setIconImage(new ImageIcon(getClass().getResource("/img/Botão.png")).getImage());
        setLocation(new java.awt.Point(200, 200));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("ID:");
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(150, 140, 60, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setText("Senha:");
        jDesktopPane1.add(jLabel3);
        jLabel3.setBounds(120, 230, 70, 30);
        jDesktopPane1.add(jTextFieldId);
        jTextFieldId.setBounds(190, 140, 220, 30);
        jDesktopPane1.add(jPasswordFieldSenha);
        jPasswordFieldSenha.setBounds(190, 230, 220, 30);

        jButton1.setBackground(java.awt.Color.white);
        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setText("Logar");
        jButton1.setToolTipText("Clique para entrar no sistema");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton1);
        jButton1.setBounds(430, 310, 100, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/TelaPrincipal.png"))); // NOI18N
        jDesktopPane1.add(jLabel2);
        jLabel2.setBounds(-220, -20, 860, 490);

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(-20, 0, 620, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        v.setSenhaUso(jPasswordFieldSenha.getText());
        v.setLoginUso(jTextFieldId.getText());
        try{
        if (consultor < 2){
        
            if(v.Entrada()){
              Desktop dt = new Desktop();
              dt.nome=v.f.getNome();
              dt.carregaNome();
              dt.tc.setVar(v.f.getGrupo());
              dt.setVar(v.f.getGrupo());
              dt.funcioLib();
                 // p.setLocationRelativeTo(null);
                dt.setVisible(true);
                 //p.setResizable(false);
                 this.dispose();
             }else{
                consultor = consultor + 1;        
            } 
             

        }else{
            JOptionPane.showMessageDialog(null, "Você errou seu login ou senha alem do permitido,"
                    + " \n O Sistema será encerrado!"
                    + "\n Se estiver com dificuldades solicite o suporte para DotTechs");
            this.dispose();
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro, "+e);
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldId;
    // End of variables declaration//GEN-END:variables

    private void iconSize(int i, int i0) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
